### ISSUE TITLE
[建议]或可通过简单css优化手机端竖屏帖子详情呈现

### ISSUE THREAD

**Issue by Dave12138** [share121/inter-knot#1557]
在`/components/popup-article.vue`的样式表中添加：
```less
@media(max-width:992px) {
    .popup-container .popup {
        width: 99% !important;

        >main {
            padding: 24px 2px !important;
            flex-wrap: wrap !important;
            overflow-y: auto !important;

            >* {
                height: unset !important;
            }

            .cover {
                flex: 1 0 100% !important;
            }
        }
    }
}

/* 部分!important可酌情删去 */
```
利用响应式特性把详情页的封面和内容改成竖排关系，可以明显提升目前竖屏体验——至于以后怎么样以后再说（
